require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReadersController do

  # This should return the minimal set of attributes required to create a valid
  # Reader. As you add validations to Reader, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReadersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all readers as @readers" do
      reader = Reader.create! valid_attributes
      get :index, {}, valid_session
      assigns(:readers).should eq([reader])
    end
  end

  describe "GET show" do
    it "assigns the requested reader as @reader" do
      reader = Reader.create! valid_attributes
      get :show, {:id => reader.to_param}, valid_session
      assigns(:reader).should eq(reader)
    end
  end

  describe "GET new" do
    it "assigns a new reader as @reader" do
      get :new, {}, valid_session
      assigns(:reader).should be_a_new(Reader)
    end
  end

  describe "GET edit" do
    it "assigns the requested reader as @reader" do
      reader = Reader.create! valid_attributes
      get :edit, {:id => reader.to_param}, valid_session
      assigns(:reader).should eq(reader)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Reader" do
        expect {
          post :create, {:reader => valid_attributes}, valid_session
        }.to change(Reader, :count).by(1)
      end

      it "assigns a newly created reader as @reader" do
        post :create, {:reader => valid_attributes}, valid_session
        assigns(:reader).should be_a(Reader)
        assigns(:reader).should be_persisted
      end

      it "redirects to the created reader" do
        post :create, {:reader => valid_attributes}, valid_session
        response.should redirect_to(Reader.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reader as @reader" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reader.any_instance.stub(:save).and_return(false)
        post :create, {:reader => {  }}, valid_session
        assigns(:reader).should be_a_new(Reader)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reader.any_instance.stub(:save).and_return(false)
        post :create, {:reader => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reader" do
        reader = Reader.create! valid_attributes
        # Assuming there are no other readers in the database, this
        # specifies that the Reader created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Reader.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => reader.to_param, :reader => { "these" => "params" }}, valid_session
      end

      it "assigns the requested reader as @reader" do
        reader = Reader.create! valid_attributes
        put :update, {:id => reader.to_param, :reader => valid_attributes}, valid_session
        assigns(:reader).should eq(reader)
      end

      it "redirects to the reader" do
        reader = Reader.create! valid_attributes
        put :update, {:id => reader.to_param, :reader => valid_attributes}, valid_session
        response.should redirect_to(reader)
      end
    end

    describe "with invalid params" do
      it "assigns the reader as @reader" do
        reader = Reader.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reader.any_instance.stub(:save).and_return(false)
        put :update, {:id => reader.to_param, :reader => {  }}, valid_session
        assigns(:reader).should eq(reader)
      end

      it "re-renders the 'edit' template" do
        reader = Reader.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reader.any_instance.stub(:save).and_return(false)
        put :update, {:id => reader.to_param, :reader => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reader" do
      reader = Reader.create! valid_attributes
      expect {
        delete :destroy, {:id => reader.to_param}, valid_session
      }.to change(Reader, :count).by(-1)
    end

    it "redirects to the readers list" do
      reader = Reader.create! valid_attributes
      delete :destroy, {:id => reader.to_param}, valid_session
      response.should redirect_to(readers_url)
    end
  end

end
